# Generated by Django 5.1.5 on 2025-01-30 05:36

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('app', '0003_blooddonationrequest'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='blooddonationrequest',
            name='email',
        ),
        migrations.RemoveField(
            model_name='blooddonationrequest',
            name='full_name',
        ),
        migrations.AddField(
            model_name='blooddonationrequest',
            name='name',
            field=models.CharField(default='active', max_length=255),
            preserve_default=False,
        ),
        migrations.AddField(
            model_name='blooddonationrequest',
            name='place',
            field=models.CharField(default='abc', max_length=255),
            preserve_default=False,
        ),
    ]
