# Generated by Django 5.1.5 on 2025-02-25 07:35

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('app', '0003_blooddonationrequest'),
    ]

    operations = [
        migrations.AddField(
            model_name='blooddonationrequest',
            name='is_active',
            field=models.BooleanField(default=True),
        ),
    ]
